services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - steam_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  steam_data: